######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 6 15:26:30 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mergesort.h nosuch.h projmap.h projmapImpl.h projset.h projsetImpl.h
SOURCES += nosuch.cpp
